let droid: Sprite = null
let gas_can: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
let mySprite = sprites.create(img`
    ..ccc..........ffffff...
    ..faac.......ffccaaff...
    ..faaac...fffccccfff....
    ..faaaacccaaaaaaaacc....
    ..cfaaccaaaaaaabbb99c...
    .caaaaaaaaaaaab111999c..
    faaacccccccaab991bbbbac.
    fffffcccaaacabbbbaaaaaac
    ...cccaaaaaaaaaaaaaaaaaf
    ...caaaaaaaaaaaaaaaaaaf.
    ...caaaaacffcaaaaaaaff..
    ....ccccffffcfffffff....
    .......ffffacaf.........
    .......ffffaccf.........
    ........ffffff..........
    ........................
    `, SpriteKind.Player)
scene.cameraFollowSprite(mySprite)
controller.moveSprite(mySprite)
for (let value of tiles.getTilesByType(assets.tile`myTile`)) {
    let gascans = 0
    gas_can = sprites.create(assets.image`gas can`, gascans)
    tiles.placeOnTile(gas_can, value)
    tiles.setTileAt(value, assets.tile`transparency16`)
}
for (let value of tiles.getTilesByType(assets.tile`myTile2`)) {
    droid = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ........ccccc...................
        ......cc99999c..................
        ....cc9d999999f.................
        ...c999dd99ff9f.................
        ....ffffd99ff9ff................
        .......f9999999f................
        .......f9999999ff...............
        ......ff99999999fff.............
        ......f699999966399cc...........
        .....cc66999966699999c..........
        .....c9366666639999999c.........
        .....c99933339b999999bcc........
        .....c99999999b99999bb99c.......
        .....c99999999bb999bb999bc......
        ......c99999999bb9bb9999bbccc...
        ......cc99999999bbbbcccccbbbcc..
        .......cc99999999999999bccffff..
        ........cccb99ccb9999bbfff......
        ........c333bb333cbbfff.........
        ........c33cc33cc3fff...........
        `, SpriteKind.Enemy)
    tiles.placeOnTile(droid, value)
    tiles.setTileAt(value, assets.tile`transparency16`)
}
